"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from ._multiprocessing_helpers import mp

if mp is not None:
    ...
operators = ...
def eval_expr(expr): # -> _ConstantValue | Any:
    """
    >>> eval_expr('2*6')
    12
    >>> eval_expr('2**6')
    64
    >>> eval_expr('1 + 2*3**(4) / (6 + -7)')
    -161.0
    """
    ...

def eval_(node): # -> _ConstantValue | Any:
    ...

@dataclass(frozen=True)
class _Sentinel:
    """A sentinel to mark a parameter as not explicitly set"""
    default_value: object
    def __repr__(self): # -> str:
        ...
    


class _TracebackCapturingWrapper:
    """Protect function call and return error with traceback."""
    def __init__(self, func) -> None:
        ...
    
    def __call__(self, **kwargs): # -> _ExceptionWithTraceback:
        ...
    


